import { Team } from './team';

export const TEAMS: Team[] = [
    { key: '1', manager: 'Denny', name: 'Team Denny', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '2', manager: 'Joe', name: 'Team Joe', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '3', manager: 'Kevin', name: 'Team Kevin', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '4', manager: 'Dave', name: 'Team Dave', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '5', manager: 'Brian', name: 'Team Brian', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '6', manager: 'Mike', name: 'Team Mike', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '7', manager: 'Jeff', name: 'Team Jeff', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '8', manager: 'Mitch', name: 'Team Mitch', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '9', manager: 'Bryan', name: 'Team Bryan', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]},
    { key: '10', manager: 'Bob', name: 'Team Bob', roster: [
        { key: '1', name: 'Tom Brady', position: 'QB', team: 'NE', team_url: 'http://espn.com', bye_week: 3, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '2', name: 'Nick Chubb', position: 'RB', team: 'CLE', team_url: 'http://espn.com', bye_week: 5, draft_rank: 1, draft_tier: 2, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'RB', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '4', name: 'Adam Thielen', position: 'WR', team: 'MIN', team_url: 'http://espn.com', bye_week: 7, draft_rank: 1, draft_tier: 1, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'WR', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'TE', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'DEF', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'K', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 },
        { key: '', name: '', position: 'BN', team: '', team_url: '', bye_week: 0, draft_rank: 0, draft_tier: 0, is_drafted: false, round_drafted: 0 }
    ]}
];
